# Generated by Django 5.1.2 on 2024-11-25 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0003_division_fuck_you"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="fuck_me",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                help_text="If you want to get fucked,please click this",
            ),
            preserve_default=False,
        ),
    ]
