# Generated by Django 5.1.2 on 2024-11-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0004_division_fuck_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="priority",
            field=models.CharField(
                choices=[("高", "High"), ("中", "Medium"), ("低", "Low")],
                default="高",
                max_length=1,
                verbose_name="优先级",
            ),
        ),
    ]
