# Generated by Django 5.1.2 on 2024-11-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0005_division_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="fuck_them",
            field=models.ImageField(
                default=False, upload_to="", verbose_name="请上传你的证件照"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="division",
            name="fuck_me",
            field=models.DateTimeField(
                help_text="If you want to get fucked,please click this",
                verbose_name="时间",
            ),
        ),
    ]
