# Generated by Django 5.1.2 on 2024-12-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0006_division_fuck_them_alter_division_fuck_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="division",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee_learning.division",
            ),
            preserve_default=False,
        ),
    ]
