# Generated by Django 5.1.2 on 2024-12-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0007_employees_division"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="employee_learning.employees",
                    ),
                ),
                ("tel", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
    ]
