# Generated by Django 5.1.2 on 2024-12-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0008_personalinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("employee", models.ManyToManyField(to="employee_learning.employees")),
            ],
        ),
    ]
