# Generated by Django 5.1.2 on 2024-12-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0009_learningcourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningcourse",
            name="level",
            field=models.CharField(
                choices=[("B", "Basic"), ("I", "Intermediate"), ("A", "Advanced")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
